# Generated by Django 4.1 on 2022-08-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("hash", models.CharField(max_length=255)),
                ("symbol", models.CharField(max_length=255)),
                ("marketcap", models.CharField(max_length=255)),
                ("price", models.CharField(max_length=255)),
                ("volume", models.CharField(max_length=255)),
                ("percent", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Crypto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
            ],
        ),
    ]
