# Generated by Django 4.0.7 on 2022-09-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='img',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
