# Generated by Django 4.0.7 on 2022-09-15 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_coin_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='update_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 15, 14, 19, 57, 678181)),
        ),
    ]
