# Generated by Django 4.0.7 on 2022-09-15 09:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_coin_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='update_date',
        ),
        migrations.AddField(
            model_name='coin',
            name='last_update_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 15, 9, 1, 5, 536891, tzinfo=utc)),
        ),
    ]
