# Generated by Django 4.0.7 on 2022-10-03 07:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_coin_update_date_coin_last_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='hash',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='coin',
            name='last_update_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 3, 7, 51, 28, 738200, tzinfo=utc)),
        ),
    ]
