# Generated by Django 4.0.7 on 2022-10-03 07:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_coin_hash_alter_coin_last_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='hash',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='last_update_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 3, 7, 53, 22, 983605, tzinfo=utc)),
        ),
    ]
